---
- name: Check and update packages
  hosts: all
  gather_facts: yes
  tasks:
    # 检查可更新的软件包，并将结果保存到变量中
    - name: Check for available package updates
      yum:
        list: updates
      register: available_updates

    # 提取需要更新的软件包信息并保存到文件
    - name: Save package names and versions to a file
      copy:
        content: |
          {% for package in available_updates.results %}
          {{ package.name }}-{{ package.version }}  # 提取软件包名和版本号
          {% endfor %}
        dest: /tmp/available_updates.txt  # 文件保存路径

    # 更新软件包到最新版本，排除内核
    - name: Update all packages except kernel
      yum:
        name: "*"       # 更新所有软件包
        state: latest   # 将软件包更新到最新版本
        exclude: kernel*  # 排除以 "kernel" 开头的软件包
      register: updated_packages

# 将已更新的软件包信息保存到文件
    - name: Save updated package names and versions to a file
      copy:
        content: |
          {% for package in updated_packages.register %}
          {{ package.name }}-{{ package.version }}  # 提取软件包名和版本号
          {% endfor %}
        dest: /tmp/updated_packages.txt  # 文件保存路径
