---
- name: Check and update packages
  hosts: all
  gather_facts: yes
  tasks:
    # 检查可更新的软件包，并将结果保存到变量中
    - name: Check for available package updates
      yum:
        list: updates
      register: available_updates

    # 提取需要更新的软件包信息并保存到文件
    - name: Save package names and versions to a file
      copy:
        content: |
          {% for package in available_updates.results %}
          {{ package.name }}-{{ package.version }}
          {% endfor %}
        dest: /tmp/available_updates.txt
